spring.application.name=VirtualWardrobe


spring.datasource.url=jdbc:mysql://localhost:3306/VirtualWardrobe_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.error.include-message=always
server.error.include-binding-errors=always

spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# AI config
ai.provider=gemini
gemini.api.key=${GEMINI_API_KEY}

# Use the mainstream flash tier model for text/vision processing
gemini.model=gemini-2.5-flash

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
