spring.application.name=VirtualWardrobe


spring.datasource.url=jdbc:mysql://localhost:3306/VirtualWardrobe_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.error.include-message=always
server.error.include-binding-errors=always

spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

# AI config
ai.provider=gemini
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash-lite
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models